= nf-bids Documentation
:navtitle: Overview
:plugin-version: 0.3.0
:nextflow-min-version: 24.10.0
:libbids-sh-version: v3.0

[.lead]
*BIDS dataset integration and closure-based channel operators for Nextflow workflows.*

nf-bids is a Nextflow plugin that parses https://bids-specification.readthedocs.io/[BIDS]
(Brain Imaging Data Structure) datasets into typed Nextflow channels and provides
closure-based operators for grouping and joining heterogeneous neuroimaging data.

== Start Here

If you want to install and run the plugin in a workflow, start in:

* xref:usage:index.adoc[User Guide]

If you want plugin internals, architecture, testing, release, or API docs, use:

* xref:development:index.adoc[Development Overview]

== Quick Example

.`nextflow.config`
[source,groovy]
----
plugins {
  id 'nf-bids@{plugin-version}'
}
----

.`main.nf`
[source,groovy]
----
include { fromBIDS; groupTupleBy } from 'plugin/nf-bids'

workflow {
  Channel.fromBIDS(params.bids_dir, params.config)
    .groupTupleBy { it.meta.subject }
    .view()
}
----

The plugin targets Nextflow {nextflow-min-version}+, ships with libBIDS.sh
{libbids-sh-version} embedded, and is published on the
https://registry.nextflow.io/plugins/nf-bids@{plugin-version}[Nextflow Plugin Registry].
